# Problem: https://leetcode.com/problems/find-the-difference/description/
"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
"""

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        t1 = set([i for i in t])
        s1 = set([i for i in s])

        t2 = [i for i in t1 if i not in s1]
        if len(t2) > 0:
            return t2[0]

        for i in s1:
            if s.count(i) != t.count(i):
                return i
